version: '3'
services:
  db:
    image: mongo:4.2.23-bionic
    #container_name: db
    restart: unless-stopped
  front:
    env_file:
       - ./melalhome/.env
   #container_name: front
    build: ./melalhome
    ports:
       - 3000:3000
   # volumes:
   #    - ./melalhome:/work
    restart: always
    restart: unless-stopped
  api:
    #container_name: api
    build: ./melalhome-node
    ports:
       - 3001:3001
    volumes:
    #  - ./melalhome-node:/work
      - ./storage:/work/public/files
    restart: always
    # command: node index.js
  webserver:
    image: nginx:1.23
    #container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./storage:/work
      - ./melalhome:/work
    restart: always
    depends_on:
      - front
      - api
#networks:
#  app-network:
#    driver: bridge 
